### ISSUE TITLE
numba compile error in collision.py

### ISSUE THREAD

**Issue by MrBurnst** [rousseau/BrainGrowth#1]
when running the test simulation on sphere5.mesh, I get a numba compilation error. Switching to collision_Tallinen.py for the collision detection works.

The stack trace:

```$ python simulation.py 
Volume of mesh is 2604.7634880788833
dt is: 2.23606797749979e-05
Traceback (most recent call last):
  File "simulation.py", line 171, in <module>
    Ft, NNLt = contactProcess(Ut, Ft, SN, Utold, nsn, NNLt, faces, nf, bw, mw, hs, hc, kc, a, gr)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 369, in _compile_for_args
    raise e
  File "/projectpath/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 326, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 658, in compile
    cres = self._compiler.compile(args, return_type)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 941, in compile_extra
    return pipeline.compile_extra(func)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 372, in compile_extra
    return self._compile_bytecode()
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 872, in _compile_bytecode
    return self._compile_core()
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 462, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 433, in frontend_looplift
    lifted=tuple(loops), lifted_from=None)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 956, in compile_ir
    lifted_from=lifted_from)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 380, in compile_ir
    return self._compile_ir()
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 879, in _compile_ir
    return self._compile_core()
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/projectpath/venv/lib/python3.6/site-packages/numba/compiler.py", line 599, in stage_inline_pass
    inline_pass.run()
  File "/projectpath/venv/lib/python3.6/site-packages/numba/inline_closurecall.py", line 89, in run
    merge_adjacent_blocks(self.func_ir.blocks)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/ir_utils.py", line 1256, in merge_adjacent_blocks
    cfg = compute_cfg_from_blocks(blocks)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/analysis.py", line 243, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "/projectpath/venv/lib/python3.6/site-packages/numba/controlflow.py", line 83, in add_edge
    assert dest in self._nodes
    AssertionError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: inline calls to locally defined closures)
```

**Comment by MrBurnst** [comment]
... it seems that this was due to using python3. the error does not appear when using python2 ...

**Comment by MrBurnst** [comment]
sorry, python2 works.
